# .streamlit/secrets.toml

EDUCATOR_HCM_KEYS = [
    "AIzaSyCM4-BBwIOdv_jJitFhqovMJ6mZ-RBWsFw",
    "AIzaSyDk3JR4N9mpG6rudOAGiRxIvBaN-hgCgwM"
]

ANALYZER_KEYS = [
    "AIzaSyCM4-BBwIOdv_jJitFhqovMJ6mZ-RBWsFw",
    "AIzaSyBZlFftkBND81n64plGpvhK2Er77p_vhYA",
    "AIzaSyCb4cBSgEUR_ynfDTUPJiYhZUaWtdvo1OU",
    "AIzaSyBeBbz81Dox61hOtaiJqRhbjhoLhfzyC_w"
]